extension_dir = "C:\\Users\\sojou\\AppData\\Local\\Microsoft\\WinGet\\Packages\\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\\ext"
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip
